// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0QAmy7w_s4PyhmYWf_Xy42moT2rtyhPE',
    appId: '1:1040737314901:web:6d323d16114812d6000cdc',
    messagingSenderId: '1040737314901',
    projectId: 'japanese-starter',
    authDomain: 'japanese-starter.firebaseapp.com',
    storageBucket: 'japanese-starter.firebasestorage.app',
    measurementId: 'G-ZG9WZ2DTT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLzIJHb-mGkNWPJPJAlzmKuN68ZeOnVXQ',
    appId: '1:1040737314901:android:69372454f1f63cf6000cdc',
    messagingSenderId: '1040737314901',
    projectId: 'japanese-starter',
    storageBucket: 'japanese-starter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW9lNKr6AR-k1MslhofI4SgMWv5Q3Ozi8',
    appId: '1:1040737314901:ios:1cb873b1eac9f6af000cdc',
    messagingSenderId: '1040737314901',
    projectId: 'japanese-starter',
    storageBucket: 'japanese-starter.firebasestorage.app',
    iosClientId: '1040737314901-m2cn6rao2ca0r2t8nvvi0eqhtj99ar7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW9lNKr6AR-k1MslhofI4SgMWv5Q3Ozi8',
    appId: '1:1040737314901:ios:1cb873b1eac9f6af000cdc',
    messagingSenderId: '1040737314901',
    projectId: 'japanese-starter',
    storageBucket: 'japanese-starter.firebasestorage.app',
    iosClientId: '1040737314901-m2cn6rao2ca0r2t8nvvi0eqhtj99ar7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0QAmy7w_s4PyhmYWf_Xy42moT2rtyhPE',
    appId: '1:1040737314901:web:81d2b5250f1fe904000cdc',
    messagingSenderId: '1040737314901',
    projectId: 'japanese-starter',
    authDomain: 'japanese-starter.firebaseapp.com',
    storageBucket: 'japanese-starter.firebasestorage.app',
    measurementId: 'G-47MCYPC1PX',
  );
}
